Repository flux-framework/dyad, pull requests merged in 2023-02, with the labels that each got.

#17 Change the name of the evironment variable for kvs namespace
  dyadrun.in
  run/dyad/dyad_startup.sh
  run/user_apps/single_step.sh
  run/user_apps/step_cons.sh
  run/user_apps/step_prod.sh
  src/lib/dyad_stream_core.cpp
  src/lib/test_stream/batch.sh
  src/modules/test/compute.c
  src/wrapper/test/combined_test.sh
  src/wrapper/test/cons_test.sh
  src/wrapper/test/prod_test.sh
  src/wrapper/test/startup.sh
  src/wrapper/wrapper.c
Labels: enhancement

#16 Wrapper: automatically detect if the file access sync need
  src/wrapper/wrapper.c
Labels: enhancement

#18 Create a ReadTheDocs page and demo for DYAD
  .clang-format
  .gitignore
  docs/Makefile
  docs/_static/Poster_2022_eScience_LLNL.pdf
  docs/_static/ShortPaper_2022_eScience_LLNL.pdf
  docs/bib/create_bibs.sh
  docs/bib/ieee.csl
  docs/bib/posters.bib
  docs/conf.py
  docs/demos/ecp_feb_2023/Makefile
  docs/demos/ecp_feb_2023/cons.c
  docs/demos/ecp_feb_2023/cons.cpp
  docs/demos/ecp_feb_2023/generation.h
  docs/demos/ecp_feb_2023/prod.c
  docs/demos/ecp_feb_2023/prod.cpp
  docs/developer_guide.rst
  docs/ecp_feb_2023_tutorial.rst
  docs/getting_started.rst
  docs/index.rst
  docs/make.bat
  docs/publications.rst
  docs/requirements.txt
Labels: documentation

#19 Fixes the includes in the C++ demo code
  docs/demos/ecp_feb_2023/cons.cpp
  docs/demos/ecp_feb_2023/prod.cpp
Labels: bug

#21 Build: Fix error with unknown header location
  src/stream/Makefile.am
  src/wrapper/Makefile.am
Labels: bug

#22 Initialization fixes and minor changes
  dyadrun.in
  run/user_apps/args.sh
  src/core/Makefile.am
  src/core/dyad_core.c
  src/core/dyad_core.h
  src/core/dyad_envs.h
  src/core/dyad_flux_log.h
  src/core/dyad_rc.h
  src/modules/Makefile.am
  src/modules/dyad_ctx.h
  src/modules/read_all.h
  src/stream/Makefile.am
  src/stream/dyad_params.hpp
  src/stream/dyad_stream_api.hpp
  src/stream/dyad_stream_core.cpp
  src/stream/dyad_stream_core.hpp
  src/stream/test/args.sh
  src/stream/test/test_stream.cpp
  src/utils/Makefile.am
  src/utils/utils.h
  src/wrapper/Makefile.am
  src/wrapper/dyad_ctx.h
  src/wrapper/test/args.sh
  src/wrapper/test/consumer_test.c
  src/wrapper/test/producer_test.c
  src/wrapper/wrapper.c
Labels: bug, enhancement
