Repository flux-framework/dyad, pull requests merged in 2024-01, with the labels that each got.

#64 bug fix for debug mode.
  CMakeLists.txt
  src/dyad/wrapper/wrapper.c
Labels: bug

#65 Build: cmake enhancement
  .github/prod-cons/dyad_prod_cons_test.sh
  .github/prod-cons/dyad_producer.sh
  .github/workflows/compile_test.yaml
  CMakeLists.txt
  cmake/configure_files/DYADConfig.cmake.in
  cmake/configure_files/dyad_config.hpp.in
  cmake/configure_files/dyad_module.lua.in
  cmake/modules/DYADUtils.cmake
  cmake/modules/FindFluxCore.cmake
  cmake/modules/FindJansson.cmake
  cmake/modules/SetupCompiler.cmake
  cmake/tests/has_filesystem.cpp
  docs/demos/ecp_feb_2023/Makefile
  include/dyad/stream/dyad_params.hpp
  include/dyad/stream/dyad_stream_api.hpp
  include/dyad/stream/dyad_stream_core.hpp
  src/dyad/CMakeLists.txt
  src/dyad/common/dyad_flux_log.h
  src/dyad/common/dyad_rc.h
  src/dyad/core/CMakeLists.txt
  src/dyad/core/dyad_core.c
  src/dyad/core/dyad_core.h
  src/dyad/core/dyad_envs.h
  src/dyad/dtl/CMakeLists.txt
  src/dyad/dtl/Makefile.am
  src/dyad/dtl/dyad_dtl.h
  src/dyad/dtl/dyad_dtl_impl.c
  src/dyad/dtl/dyad_dtl_impl.h
  src/dyad/dtl/flux_dtl.c
  src/dyad/dtl/flux_dtl.h
  src/dyad/dtl/ucx_dtl.c
  src/dyad/dtl/ucx_dtl.h
  src/dyad/modules/CMakeLists.txt
  src/dyad/modules/dyad.c
  src/dyad/stream/CMakeLists.txt
  src/dyad/stream/dyad_stream_core.cpp
  src/dyad/utils/CMakeLists.txt
  src/dyad/utils/base64/CMakeLists.txt
  src/dyad/utils/read_all.c
  src/dyad/utils/read_all.h
  src/dyad/utils/utils.c
  src/dyad/utils/utils.h
  src/dyad/wrapper/CMakeLists.txt
  src/dyad/wrapper/wrapper.c
Labels: enhancement

#63 Reinit
  include/dyad/stream/dyad_params.hpp
  include/dyad/stream/dyad_stream_core.hpp
  pydyad/pydyad/bindings.py
  src/dyad/core/dyad_core.c
  src/dyad/core/dyad_core.h
  src/dyad/core/dyad_envs.h
  src/dyad/stream/dyad_stream_core.cpp
  tests/integration/dlio_benchmark/dyad_torch_data_loader.py
Labels: enhancement

#77 Consume after kvs pull
  pydyad/pydyad/bindings.py
  pydyad/pydyad/context.py
  src/dyad/common/dyad_structures.h
  src/dyad/core/dyad_core.c
  src/dyad/core/dyad_core.h
  src/dyad/dtl/dyad_dtl_api.c
  src/dyad/dtl/dyad_dtl_api.h
  src/dyad/dtl/flux_dtl.c
  src/dyad/dtl/ucx_dtl.c
  src/dyad/dtl/ucx_dtl.h
  src/dyad/dtl/ucx_ep_cache.cpp
  src/dyad/dtl/ucx_ep_cache.h
  src/dyad/modules/dyad.c
  tests/integration/dlio_benchmark/configs/workload/dyad_unet3d.yaml
  tests/integration/dlio_benchmark/dyad_torch_data_loader.py
Labels: bug, enhancement

#79 Switch DYAD to use RMA instead of 2 sided communication for better performance
  .github/workflows/compile_test.yaml
  CMakeLists.txt
  cmake/configure_files/dyad_config.hpp.in
  src/dyad/common/dyad_rc.h
  src/dyad/core/dyad_core.c
  src/dyad/dtl/dyad_dtl_api.h
  src/dyad/dtl/ucx_dtl.c
  src/dyad/dtl/ucx_dtl.h
  src/dyad/dtl/ucx_ep_cache.cpp
  src/dyad/modules/dyad.c
  tests/integration/dlio_benchmark/configs/workload/dyad_unet3d.yaml
  tests/integration/dlio_benchmark/configs/workload/unet3d_base.yaml
  tests/integration/dlio_benchmark/perf_analysis/dlp_analyzer-checkpoint.ipynb
  tests/integration/dlio_benchmark/setup-env.sh
Labels: enhancement
